import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  tutorialSidebar: [
    "render-ui",
    {
      type: "category",
      label: "Text 组件",
      items: ["Text/manage-docs-versions", "Text/translate-your-site"],
    },
    {
      type: "category",
      label: "View 组件",
      items: ["View/1", "View/2", "View/3", "View/4", "View/5"],
    },
  ],
};

export default sidebars;
